# Generated by Django 4.0 on 2023-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
