# Generated by Django 4.0 on 2023-04-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('modelName', models.CharField(max_length=20)),
                ('type_of_port', models.CharField(max_length=20)),
                ('type_of_part', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_id', models.GenericIPAddressField()),
                ('year_purchase', models.DateTimeField(auto_now_add=True)),
                ('purchase_cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
    ]
