# Generated by Django 4.0 on 2023-04-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_biometric_cameras_switch_vlan_wifi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameras',
            options={'verbose_name_plural': 'cameras'},
        ),
    ]
