# Generated by Django 4.0 on 2023-04-24 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_biometric_options_alter_server_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometric',
            name='vlan_id',
        ),
        migrations.RemoveField(
            model_name='cameras',
            name='vlan_id',
        ),
        migrations.AddField(
            model_name='biometric',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameras',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 12, 53, 19, 517259, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 12, 53, 26, 265344, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='switch',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 12, 53, 37, 915431, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vlan',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 12, 53, 42, 220283, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wifi',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 12, 53, 50, 177210, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biometric',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cameras',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='switch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='switch',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wifi',
            name='year_purchase',
            field=models.DateField(null=True),
        ),
    ]
