# Generated by Django 4.0 on 2023-04-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_biometric_vlan_id_remove_cameras_vlan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biometric',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='cameras',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='server',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='vlan',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
        migrations.RenameField(
            model_name='wifi',
            old_name='year_purchase',
            new_name='date_purchase',
        ),
    ]
